# Generated by Django 3.0.3 on 2020-06-28 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200628_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Create_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='Create_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
