# Generated by Django 3.0.3 on 2020-06-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200628_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Create_Date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Create_Date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Published_Date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
    ]
